### ISSUE TITLE
Cluster.Cmd assumes first parameter is key

### ISSUE THREAD

**Issue by rameshvk** [fzzy/radix#60]
In radix/extra/cluster/cluster.go line 402

```go
	key, err := keyFromArg(args[0])
```

The assumption is that cluster key is the first argument.  This is not true for a few REDIS commands, the most useful of which is EVALSHA.  Is there a suggested workaround?  I have modified the library to support a new method CmdWithKey which explicitly accepts the Key as follows:

```go
func CmdWithKey(cmd, key string, args ...interface{})  *redis.Reply  {
... same as Cmd but the key is explicit...
}
```

Is this something I should do a pull request on or is there a different way this should be dealt with in this library? 

Note that it is possible to use GetClientForKey but unfortunately GetClientForKey does not release the client to the pool which is not acceptable as if there is a lot of EVALs it would end up creating a connection per request.

**Comment by mediocregopher** [comment]
Hi there, and thanks for submitting the issue!

So you're correct in that at the moment there's not a good way to handle this situation. My immediate reaction is to point you at [radix.v2](https://github.com/mediocregopher/radix.v2) which I've been working on and (despite the bold text in the README) is essentially stable and I'm going to release very soon. I've actually done this exact use-case (lua scripts with a cluster) with radix.v2, so I'm pretty confident this would work for you. The new package has largely the same concepts as this one, but with some naming cleanup and a significantly nicer interface for working with pools.

I totally understand you're working on a large project and switching would be a giant hassle though. In that case I'd like to re-look at the code and see why exactly connections cannot be returned to their pools inside the cluster (I was able to do it in v2, but I forget some aspects of this codebase already). If it's possible I'll likely just add in a `Put` style method so you can re-add your connections to their pool. But if that doesn't pan out I'd definitely be willing to take a look at your PR :)

**Comment by rameshvk** [comment]
I looked at redis.v2 and it is indeed going to work for my case.   Would you say radix.v2 is weeks away or months away?

I don't think it is worth changing v1 given v2 is so close -- I was indeed going by the README.

Thanks for the fast response!

**Comment by mediocregopher** [comment]
I'm at the point where for every package in v2 except the `util` package I would commit to that as the stable API. I'm like 90% sure about the `util` package as well but I'm holding out since I added it somewhat recently. In a week or two I'll be sure and will take down that banner in the likely event that I haven't decided to change something. But again, for the rest of the packages I'll say they're already stable and are not going to change.

And no problem :P

**Comment by mediocregopher** [comment]
Ok, so I eat my words. There is one change I'd like to make to cluster, but it's likely not very major. I would like to move the `KeyFromArgs` function into the main `redis` package, since I'd like to use it inside util and there's nothing which really makes it cluster specific. If this would majorly mess you up let me know and I can hold off.

**Comment by rameshvk** [comment]
No, that won't affect me at all.  Please go ahead and thanks for checking!

**Comment by mediocregopher** [comment]
Awesome, I just pushed up an addition to util, here: http://godoc.org/github.com/mediocregopher/radix.v2/util#LuaEval

You might find it useful for your use-case

**Comment by mediocregopher** [comment]
@rameshvk I'm gonna assume your problem has been taken care of and close this out. If that's not the case please feel free to re-open it :)
