### ISSUE TITLE
except blocking but returning

### ISSUE THREAD

**Issue by AssassinPig** [fzzy/radix#71]
Hi all:
   I worte codes  like this: 
   ```
   c, err2 := con.Cmd("BRPOP", TODO_LIST, 1).List()
   ```
  I expected it would be blocked here but it still return. So Is it an issue???

**Comment by mediocregopher** [comment]
Hey there! The `1` you have as your last parameter to `Cmd` is the timeout for the command. redis will block for that many seconds, and then return `nil` if there hasn't been any values yet. You can check out the docs [here](http://redis.io/commands/blpop) for the semantics on how blpop/brpop behave.

If you want to block forever, you can specify a `0` as the timeout. However keep in mind that if you want to do this you cannot have set a timeout when creating the redis client, otherwise it will still unblock with a network error and things will get weird.

**Comment by AssassinPig** [comment]
@mediocregopher thx!
