### ISSUE TITLE
Using pool and get err "use of closed network connection"

### ISSUE THREAD

**Issue by coseyo** [fzzy/radix#72]
When I init a pool and I didn't call any cmd for a long time. Then I call a  c, err :=pool.Get() to get a client and use it : c.Cmd("get", "test").Str(), it will occur error "use of closed network connection".

So I have to change the code below:

```go
type redisPool struct {
	P *pool.Pool
}

var (
	RedisPool redisPool
)

func InitPool(network, addr string, size int) error {
	var err error
	RedisPool.P, err = pool.NewPool(network, addr, size)
	return err
}

func (this *redisPool) Get() (*redis.Client, error) {
	c, err := this.P.Get()
	if err != nil {
		return nil, err
	}

	e := c.Cmd("ping").Err
	if e != nil && e.Error() == "EOF" {
		return this.Get()
	}
	return c, nil
}

```

Is there any other way to get it through ?

**Comment by mediocregopher** [comment]
So the likely root of the problem here is that the connections are going unused for so long that they are being closed, for one reason or another. Since `pool` has no go-routine of its own to perform this kind of checking/cleanup with, it's kind of up to the user to deal with the problem if they see it.

A simpler way to do what you're doing would be to spawn up a go-routine which loops forever, and every second pulls a connection out of the pool, does a ping, and puts the connection back if it's still alive. This will both cleanup dead connections as well as keep alive ones active, without you needing to override the `Get` behavior.

As a side-note, if you haven't already I'd recommend you check out (radix.v2)[https://github.com/mediocregopher/radix.v2]. It has a number of new features, significant performance improvements, and an easier to use pool package (although this particular problem will still be present in that one as well). I'm not maintaining this one anymore, except for any bug-fixes which pop up.

Hope this helps!

**Comment by coseyo** [comment]
thanks @mediocregopher ,I think I should rewrite a pool lib to solve this problem.The pool should have a clientTimeout param, when getting a client should check the client is timeout or not.

**Comment by mediocregopher** [comment]
Well whatever solution works for you :) let me know if you have anymore questions!

**Comment by coseyo** [comment]
Haha, I will.
