### ISSUE TITLE
Question: Do you need to close connections that are drawn from pool?

### ISSUE THREAD

**Issue by david4shure** [fzzy/radix#76]
Lets say for an example I have the following code.

```golang
package main

import (
        "github.com/fzzy/radix/extra/pool"
)

func main() {
        // Initialize connection pool
        pool, err := pool.NewPool("tcp", "someaddr:6379, 10)
        defer pool.Empty()
        // ...
        client, err := pool.Get()
        defer client.Close()
}

```

In this example, is it necessary close the connection which has been drawn from the connection pool? 

So I am `defer client.Close` even though I have drawn the connection from a pool, is this still necessary?

**Comment by mediocregopher** [comment]
You definitely don't want to close the connections, actually. The idea of a connection pool is that you keep around a number of open connections that are ready to be used at any moment, so every time you need a connection you don't incure the cost of creating a new one. Instead of closing the connection, you will want to put it back in the pool.

On another note, this version of radix is no longer supported, there's a [v2](https://github.com/mediocregopher/radix.v2) which is actively supported, and which also has a much more convenient implementation of a connection pool. I highly recommend you check that one out.

Thanks!
